language: node_js

node_js:
  - "lts/carbon"

cache:
  directories:
    - "node_modules"

script:
  - '[ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm run test; fi'
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run verify; fi'

git:
  depth: 5