language: node_js

node_js:
  - "lts/carbon"

cache:
  directories:
    - "node_modules"

script:
  - '[ "$TRAVIS_PULL_REQUEST" != "false" ] && npm run test'
  - '[ "$TRAVIS_PULL_REQUEST" = "false" ] && npm run verify'

git:
  depth: 5